# Docker compose file for building docker images and running locally

version: '3.8'

services:
  book_catalog:
    build:
     context: ./book_catalog
     dockerfile: Dockerfile
    ports:
      - "8001:80"
    environment:
      - DATABASE_URL=postgresql://sit722_7_2p_8qxq_user:yGwBMEG93f1EZJAF9bCDToONRh6UCB8K@dpg-crkq23rtq21c73deun7g-a.oregon-postgres.render.com/sit722_7_2p_8qxq
    networks:
      - app-networks

  inventory_management:
    build:
     context: ./inventory_management
     dockerfile: Dockerfile
    ports:
      - "8002:80"
    environment:
     - DATABASE_URL=postgresql://sit722_7_2p_8qxq_user:yGwBMEG93f1EZJAF9bCDToONRh6UCB8K@dpg-crkq23rtq21c73deun7g-a.oregon-postgres.render.com/sit722_7_2p_8qxq
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge