# Kubernetes deployment file to deploy book_catalog and inventory_management microservices to aks

apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: sit722week7task2.azurecr.io/book_catalog:1.1.1
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722_7_2p_8qxq_user:yGwBMEG93f1EZJAF9bCDToONRh6UCB8K@dpg-crkq23rtq21c73deun7g-a.oregon-postgres.render.com/sit722_7_2p_8qxq"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: sit722week7task2.azurecr.io/inventory_management:1.1.1
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722_7_2p_8qxq_user:yGwBMEG93f1EZJAF9bCDToONRh6UCB8K@dpg-crkq23rtq21c73deun7g-a.oregon-postgres.render.com/sit722_7_2p_8qxq"


---

apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  
  